name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Publish
      run: | 
        # Define some variables for things we need
        tag=$(git describe --tags --abbrev=0)
        release_name="NFAuthenticationKeyCli-$tag-${{ matrix.target }}"

        # Build everything
        dotnet publish --framework netcoreapp3.1 -c Release -o "$release_name"

        # Pack files
        zip -r "${release_name}.zip" "$release_name"

        # Delete output directory
        rm -r "$release_name"
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "NFAuthenticationKeyCli-*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
